# Configuration for Haifa Bay Vessel Image Scraper

# Google Cloud Storage Configuration
gcs:
  bucket_name: outsource_data
  credentials_path: "C:\\Users\\OrGil.AzureAD\\OneDrive - AMPC\\Desktop\\Azimut.ai\\cloud upload\\credentials.json"
  
  # Paths within the bucket
  paths:
    # Where to save new scraped images
    upload_base: "reidentification/bronze/raw_crops/ship_spotting"
    
    # Where to check for existing IMOs (broader path to check all sources)
    check_base: "reidentification/bronze/raw_crops"

# API Configuration
api:
  datalastic_key: "b123dc58-4c18-4b0c-9f04-82a06be63ff9"
  
# Port Configuration (Haifa Bay)
port:
  name: "Haifa Bay"
  latitude: 32.8154
  longitude: 35.0043
  search_radius_km: 15

# Scraping Configuration
scraping:
  max_photos_per_imo: 150
  max_gallery_pages: 10
  batch_size: 10
  
  # Network settings
  connect_timeout: 8.0
  read_timeout: 12.0
  max_retries: 3
  retry_backoff_base: 1.0
  min_request_delay: 0.05
  max_request_delay: 0.12
  
  # Concurrency settings
  gallery_workers: 4
  image_download_workers: 12
  max_concurrent_downloads: 20
  
  # Image download settings
  stream_chunk_size: 8192

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s [%(levelname)s] %(message)s"
  datefmt: "%H:%M:%S"